### ISSUE TITLE
Bug in ETL Pipeline Validation

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#1505]
The ETL pipeline should emit an error for a given column only if one of the following conditions is true:

* The datatype of the value is not correct according to the property constraint.
* The value is required, but no value exists

The second condition is not being checked correctly; there are many cases where an error is being reported for a null value even if the `minCount` constraint is set to zero (i.e. the property is optional).  This needs to be fixed.

This issue appears to be the root cause of  EDWA-4229, EDWA-4145, EDWA-4146.

**Comment by Uvashriamm** [comment]
Greg,
The issue seems like

In SourceDataDictionarySheet.java , method getRdfDatatype
We are considering the bit as Integer value

```
                  case "BIT" :
				constraint.setMinInclusive(0);
				constraint.setMaxInclusive(1);
				return XMLSchema.INTEGER;
```

And in BasicJavaDatatypeMapper, method  javaDatatype
We returning Long of the Integer datatype
```
	if (XMLSchema.INTEGER.equals(rdfDatatype)) {
			return Long.class;
	}
```

And so we are getting the method as longValue in the generated ReadShapeFn class.

Say for example,
In SourceDataDictionary datatype for the Field IsCoastingSchool is bit
In holistic-customer-model datatype for the property IsCoastingSchool is boolean 

Here I think we have to correct the datatype validation for booleanValue method instead of longValue.

Can we consider the bit as boolean in SourceDataDictionarySheet getRdfDatatype method ?

**Comment by gmcfall** [comment]
I can understand the benefits of treating BIT as a boolean, but SQL has a BOOLEAN type.

I worry that introducing an _implicit_ conversion to boolean might not always do the right thing.  
For instance, there might be cases where the value needs to be added or subtracted from some other integer value.

The correct way to handle conversions of BIT to boolean is an explicit transformation, such as:

```
  targetValue := 
      CASE
          WHEN $.sourceValue = 1 THEN true
          WHEN $.sourceValue = 0 THEN false
      END
```

Our validation should be smart enough to confirm that the `targetValue` is a boolean even though the `sourceValue` is an integer.

Finally, you should be validating based on Java types.  In other words, convert the data type from the Property Constraint and the data value received from the source system to Java types, and compare the Java types.  If the Java types are compatible then, no error.

**Comment by gmcfall** [comment]
I'm going to close this issue.  Validation of data type should happen at compile time (not at runtime).  We'll add a new issue to the backlog for this.
