### ISSUE TITLE
Bug in App Generator

### ISSUE THREAD

**Issue by Uvashriamm** [konigio/konig#563]
While generating the app.yaml file the "containers" should be generate as "container"

**Comment by gmcfall** [comment]
The app.yaml file is generated by the following method:
```
   io.konig.data.app.common.DataApp#generateAppConfigFil
```

The serialization is done via `Yaml.write`.

Notice that we are simply serializing a `io.konig.data.app.common.DataApp` instance.

The problem is that `DataApp` has a getter named `getContainers`.

The simplest solution is to refactor the `DataApp` class and rename `getContainers` to `getContainer`.
