### ISSUE TITLE
Single dataset for the Shapes

### ISSUE THREAD

**Issue by Uvashriamm** [konigio/konig#582]
Now the tool is generating the dataset based on the Prefix of the Target class.

I want to maintain the tables under the common single dataset.

**Comment by gmcfall** [comment]
This capability already exists!

You just need to override the default value for the `gcpDatasetId` configuration setting.

The [settings.properties](https://github.com/konigio/konig/blob/master/konig-spreadsheet/src/main/resources/WorkbookLoader/settings.properties) file contains the following defaults:

```
gcpDatasetId: {classNamespacePrefix}
bigQueryTableId: {classLocalName}
gcpBucketName: {shapeLocalNameLowercase}-{gcpBucketSuffix}
gcpBucketStorageClass: multi_regional
gcpBucketLocation: us
```

To override the value of the `gcpDatasetId` setting,  add a new Sheet with the following data...

| Setting Name | Setting Value      |
|----------------|--------------------|
| gcpDatasetId | pearsonmypedia |

I've already done this for [mypedia-datamodel-v2](https://docs.google.com/a/pearson.com/spreadsheets/d/1gyhKGRpH4M3wyJFsl63eKbComSXVql41MiJQZr31G4s/edit?usp=sharing), and I have confirmed that it builds a single dataset for the resources defined in the sheet.

This mostly works.  There is one minor edge case.  The tool also builds a Table named `metadata.FieldLabel` which stores metadata about the tables.  Right now, this dataset is hard-coded to `metadata`.  I'll add a configuration setting so that you can control the dataset for this table.

**Comment by gmcfall** [comment]
I have added a configuration setting that allows you to control the dataset of the FieldLabel table.
Within the multi-project `pom.xml`, you should add a `<metadata>` element as shown below...

```
  ...
<googleCloudPlatform>
     <enableBigQueryTransform>true</enableBigQueryTransform>
     <bigquery>
         <metadata>
             <dataset>pearsonmypedia</dataset>
         </metadata>
     </bigquery>
</googleCloudPlatform>
```
