### ISSUE TITLE
Continuous Integration deployment of Snapshot artifacts to Nexus

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#598]
When code is committed to GitHub, I want snashot artifacts to be deployed automatically to a Nexus repository.

Ideally, artifacts should be deployed to https://oss.sonatype.org/content/repositories/snapshots
If that's not possible, then we should use the Pearson Nexus repository.

Ideally, this should be handled by the existing Travis CI server.
If that's not possible, we should use a Pearson Jenkins server.

**Comment by zednis** [comment]
from http://central.sonatype.org/pages/ossrh-guide.html

## Introduction
Sonatype OSSRH (OSS Repository Hosting) uses Sonatype Nexus Repository Manager to provide repository hosting service for open source project binaries - be sure to review the full terms of service. OSSRH uses the Maven repository format and allows you to:

* deploy development version binaries (snapshots)
* stage release binaries
* promote release binaries and sync them to the Central Repository

The initial setup for your OSSRH repository requires some manual steps and human review (see why), after which your deployment process is typically modified to get components into OSSRH. **These are all one time steps.**

After the initial setup, publishing from OSSRH to Central is a trivial action which can be done via a browser or programmatically.

## Initial Setup
### Create a ticket with Sonatype
Sonatype uses JIRA to manage requests.

1) [Create your JIRA account](https://issues.sonatype.org/secure/Signup!default.jspa)
2) [Create a New Project ticket](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134)

This triggers creation of your repositories. Normally, the process takes less than 2 business days. Why the wait?

Helpful videos:
* [Claim your Namespace on the Central Repository](https://youtu.be/P_3yo-oU1To)
* [Applying for Access to OSSRH](https://youtu.be/0gyF17kWMLg)

Please do not deploy until after you have received an e-mail notice indicating that the ticket is Resolved. One of the most common problems related to new projects is premature deployment, which misroutes your artifacts to a catch-all repository.

Lastly, if your component is already in Central be sure to note this in your ticket, and review how to [migrate to OSSRH](http://central.sonatype.org/articles/2014/Feb/27/migrating-a-project-to-ossrh).

### Review Requirements
There are basic metadata and content requirements for components available in Central. We recommend getting familiar with them while your repositories are being created. For the details, see [Central Component Requirements](http://central.sonatype.org/pages/requirements.html).

Helpful videos:
* [Requirements and Signing Tips](https://youtu.be/DE3FVty3NgE)
* [Project Object Model POM?!](https://youtu.be/N7KXuvi_2SE)
* [Javadoc, Sources and Signing](https://youtu.be/HeQ70mRSSGE)

### Deployment
Most developers find it easiest to implement a deployment procedure in order to automatically meet the component requirements. Depending on your choice of tools and approach there are many different do this.

Below is information for popular tools and approaches. Feel free to send notes about alternative approaches or corrections.

* [Apache Maven](http://central.sonatype.org/pages/apache-maven.html)
* Apache Ant
* Gradle
* sbt
* [Manual Staging Bundle Creation and Deployment](http://central.sonatype.org/pages/manual-staging-bundle-creation-and-deployment.html)

Note: There is a limit of roughly 1024MB on any single file uploaded to OSSRH. Your uploads will fail with a broken pipe exception when you hit this limit. Contact us directly if you need to upload larger components.

Helpful videos:
* [First Deployments](https://youtu.be/dXR4pJ_zS-0)

### Releasing to Central
At this point, your project is deployed to private repository only accessible to your project members.

To release your components, you can either release them directly from the command line, if you are using the Nexus Staging Maven Plugin or Ant Tasks or open your favorite browser and go to https://oss.sonatype.org/ or follow our [detailed instructions](http://central.sonatype.org/pages/releasing-the-deployment.html).

Helpful videos:
* (Accessing OSSRH](https://youtu.be/b5D2EBjLp40)

Upon release, your component will be published to Central: this typically occurs within 10 minutes, though updates to search can take up to two hours.

**Comment by zednis** [comment]
Having looked at the existing io.konig release packages and project configuration I think everything is set from sonatype's side for the project to be able to deploy to snapshots.

To setup deployment of snapshots to sonatype as a result of a successful Travis-CI build a few updates to the project configuration will be required.

1) Add a deploy section to the travis-ci config specifying that ``mvn deploy`` should be executed on a successful build of the master branch.  The master branch is specified so we don't deploy snapshots as the result of every branch update.

```
deploy:
  provider: script
  script: "mvn deploy --settings travis-settings.xml -DskipTests=true"
  skip_cleanup: true
  on:
    branch: master
```
Add a travis-settings.xml file which is used as the settings.xml by ``mvn deplooy``

travis-settings.xml:
```
<settings
        xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <servers>
        <server>
            <!-- Maven Central Deployment -->
            <id>ossrh</id>
            <username>${env.SONATYPE_USERNAME}</username>
            <password>${env.SONATYPE_PASSWORD}</password>
        </server>
    </servers>
</settings>
```
SONATYPE_USERNAME and SONATYPE_PASSWORD are environment variables and can be setup us  [Encrypted Environment Variables](https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables) or as hidden variables set via the repository project settings through the Travis-CI web interface at https://travis-ci.org/konigio/konig/settings.

**Comment by zednis** [comment]
@gmcfall Is the option``-DperformRelease=true`` from the mvn deploy line in deploy.sh equivalent to ``mvn clean deploy -P release`` as described in the [Sonatype Maven release documentation](http://central.sonatype.org/pages/apache-maven.html#performing-a-release-deployment)?

I see in the parent POM that it sets a release-profile profile, but I don't see any other references in any of the project POMs to that profile.  Is that profile id a default that is understood by the nexus staging maven plugin?  Or the javadoc generation plugins?

**Comment by gmcfall** [comment]
I have added the SONATYPE_USERNAME and SONATYPE_PASSWORD environment variables via the web interface at https://travis-ci.org/konigio/konig/settings.

**Comment by zednis** [comment]
I have merged pull request https://github.com/konigio/konig/pull/631 which updates the Travis-CI configuration and package version numbers to facilitate deployment of snapshots by Travis-CI to sonatype on a successful build.

I will update this ticket after confirming that snapshots were successfully deployed.

**Comment by zednis** [comment]
The snapshots for 2.0.0-8-SNAPSHOT appear to have successfully deployed to https://oss.sonatype.org/content/repositories/snapshots/io/konig/.

example - https://oss.sonatype.org/content/repositories/snapshots/io/konig/konig-core/2.0.0-8-SNAPSHOT/

The Travis-CI build completed in 5 min 17 sec (I am not sure how much of that time was spent on the initial build and test vs the deploy).  Travis-CI will only deploy on successful builds of the master branch so the duration of build jobs on non-master branches should be unchanged.

@gmcfall I think this ticket is ready to be closed now.

**Comment by gmcfall** [comment]
The deployments are failing.  Let's get them working again.
