### ISSUE TITLE
Generate JSON Schema from sample JSON

### ISSUE THREAD

**Issue by gmcfall** [konigio/konig#859]
I want a tool that will generate JSON schema from sample JSON.  (Build or find Open Source)

**Comment by zednis** [comment]
There is an online web app at https://www.jsonschema.net/ that can generate JSON Schema from example JSON documents, but I don't see much information on what backend library they are doing to generate the schema.

The [webpage]( https://jackwootton.github.io/json-schema/) describing the app indicates that no input data is stored so I don't think using it would be a security risk (especially since we would only be sending fake, non-sensitive JSON example data)

**Comment by zednis** [comment]
I have generated a Product MDM JSON Schema from an example 'fake' JSON document.  It will need some minor adjustment since the example data contained many fields with null values and the correct datatype for the field could not be discerned by the schema generation tool.

I should be able to reference the MDM Generic Outbound Attributes spreadsheet to discern what the expected field datatypes would be.

Another issue I am noticing with the Product MDM example is that fields which should be numbers are represented as strings.

```json
"fixedDaysSupply": "90",
```

I think we can resolve this by using the ``format`` property of JSON schema to indicate that this string value should be interpreted as an integer/decimal/etc.

**Comment by zednis** [comment]
For generating the initial product MDM JSON schema, I have developed a workflow that of two steps

Preconditions:
- ensure all fields that need to be represented in the schema are present in the example instance document.

**1. Use jsonschema.net to generate a base JSON schema from an example JSON instance document**

Go to https://jsonschema.net/ to generate a basic JSON Schema from the example JSON document.

Recommended schema options:
- Annotations - select only 'Infer Examples'
- Common Assertions - select only 'INCL null as type'

All other schema options can be left at default.

All fields in the resulting schema will be nullable and optional and their type will be inferred based on the type from the input example instance document.  

One issue we noted is that the schema generator does not properly handle cases where the objects in an array have different structure.  The generator will define an item schema based on the first item found in the array and will not check if subsequent items conform to a different structure.

for example, the input JSON had the following structure
```
"productUserDefinedAttributes":[  
            {  
               "pricingInfoAttributes":[  
                  {  
                     "countryCurrency":"United Kingdom, Pounds",
                     "isFinalPrice":"N",
                     "type":"List Price",
                     "value":"12.5",
                     "salesTaxAmount":"99998"
                  }
               ]
            },
            {  
               "attributeGroupName":"PSON_COURSEWARE_DETAILS_ORG",
               "attributeGroupDisplayName":"Courseware Details (Org)",
               "multiRowFlag":"N",
               "userAttributes":[  
                  {  
                     "attributeRecordIdentifier":"126976741",
                     "attributeName":"ANSWER_BOOK_RESTRICTION",
                     "displayName":"Answer Book Restriction",
                     "value":"N/A",
                     "valueType":"C"
                  }
               ]
            }
]   
```
and the generator missed defining an object with properties ``attributeGroupName``, ``attributeGroupDisplayName``, ``userAttributes``, etc.

In this case the error was caused by what is clearly a bug in the input JSON, but in other cases it may be caused by intended input which is not easily fixable.  The fix will be to manually edit the generated schema to include all item object schemas in a [``"anyOf"``](https://spacetelescope.github.io/understanding-json-schema/reference/combining.html) array.

Also of note - the JSON document we generated a schema for represents numerical values using strings.  We handle this case in step 2.

**2. Use script to enhance generate schema with field format information**

There is an external spreadsheet which captures additional field information not inferable from the example instance document; we developed a script to read this external document and update the json schema with this additional information.

Currently the script enhances the 
- format information for string fields that encode numerical or date data
- maxLength values for string fields

The script is available at https://github.com/zednis/json2shapes/blob/master/enrich_schema.py and is currently customized to read the Product MDM bible spreadsheet.  In the future this script should be generalized to take in a generic data dictionary structure.
